// Indian states and union territories
export const INDIA_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  // Union Territories
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

// Popular international destinations
export const COUNTRIES = [
  "India",
  "UAE",
  "Thailand",
  "Maldives",
  "Sri Lanka",
  "Nepal",
  "Bhutan",
  "Singapore",
  "Malaysia",
  "Indonesia (Bali)",
  "Vietnam",
  "Cambodia",
  "Japan",
  "South Korea",
  "Turkey",
  "Egypt",
  "Kenya",
  "South Africa",
  "France",
  "Italy",
  "Switzerland",
  "United Kingdom",
  "USA",
  "Australia",
  "New Zealand",
  "Canada",
  "Greece",
  "Spain",
  "Portugal",
  "Russia",
  "China",
  "Hong Kong",
  "Mauritius",
  "Seychelles",
  "Jordan",
  "Saudi Arabia",
  "Oman",
  "Qatar",
  "Bahrain",
  "Kuwait",
];
